services:
  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookinghub
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  bookinghub-app:
    container_name: bookinghub-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - 3000:3000  # Expose Next.js app
    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - prisma-network

volumes:
  pgdata:

networks:
  prisma-network:
    name: prisma-network
